### ISSUE TITLE
[BUG] `apktool b` generates bad `hiddenapi_class_data_item`

### ISSUE THREAD

**Issue by RenateUSB** [iBotPeaches/Apktool#2918]
### Information
1. Apktool Version 2.6.1
2. Windows 10
3. Onyx Poke3 framework.jar, but narrowed down some

The original problem was that `apktool d -api 29`, `apktool b -api 29` succeeded but the resulting jar did not work.
The deeper dive of `apktool d -api 29`, `apktool b -api 29`, `apktool d -api 29` gave the below error.
I then did a fresh `apktool d -api 29` and tested it with `apktool b -api 29`, `apktool d -api 29`.
I deleted classes as much as I could until the `apktool b -api 29`, `apktool d -api 29` returned no error, then backed up.
At this point it consisted of only two smali classes that still gave the same error.
Deleting various virtual methods from ProtoOutputStream might cause the error to go away, or not.
I also cleaned all `greylist-max-?` to simple `greylist`
Various versions caused the OOB to be 7 instead of 6.

1. baksmali is using an array of length 6 to be indexed by 3 bits (masked by 0x7), a recipe for disaster.
2. apktool is still using baksmali that does not support `greylist-max-r`. (This example never used `greylist-max-r`.)
3. Even the hidden API flags that it did decode are all wrong, many `greylist` were changed to `whitelist`. `writeRepeatedFixed32Impl(II)V` even changed from `greylist` to `blacklist`.

### Stacktrace/Logcat

```
Error occurred while disassembling class Landroid.util.proto.ProtoOutputStream; - skipping class
java.lang.ArrayIndexOutOfBoundsException: 6
        at org.jf.dexlib2.HiddenApiRestriction.getAllFlags(HiddenApiRestriction.java:108)
        at org.jf.dexlib2.dexbacked.DexBackedMethod.getHiddenApiRestrictions(DexBackedMethod.java:204)
```

### Steps to Reproduce
1. `unzip fw.zip`
2. `apktool b FW0 -o fw1.jar -api 29`
3. `apktool d fw1.jar -o FW1 -api 29`

[fw.zip](https://github.com/iBotPeaches/Apktool/files/9920693/fw.zip)

**Comment by RenateUSB** [comment]
Ok, here is a further case, similar to the preceeding one.
It does not generate the error of the preceeding one but it does screw up the hidden API markers.
This example still has the problematic ProtoStream class, ProtoOutputStream was removed.
It has a demo class of HapiObject (super java.lang.object) and HapiProto (super android.util.proto.ProtoStream).
HapiObject is happy with the hidden API markers propagated.
HapiProto has all the markers changed to `greylist`
ProtoStream, as before, has changes to the markers.
This is (part of) the original smali code of both Hapi files.
```
.field public whitelist HAPI0_whitelist:I

.field public greylist HAPI1_greylist:I

.field public blacklist HAPI2_blacklist:I

.field public greylist-max-o HAPI3_greylist_max_o:I

.field public greylist-max-p HAPI4_greylist_max_p:I

.field public greylist-max-q HAPI5_greylist_max_q:I
```

Steps to Reproduce

1. unzip hapi.zip
2. apktool b FW0 -o fw1.jar -api 29
3. apktool d fw1.jar -o FW1 -api 29
4. Examine FW1\smali\android\util\HapiProto.smali

[hapi.zip](https://github.com/iBotPeaches/Apktool/files/9922127/hapi.zip)

**Comment by RenateUSB** [comment]
Ok, we're narrowing it down!
The problem is if a class has a super with a `greylist` constructor.
We're even back to getting that array OOB error.
ProtoStream has been pruned down to nothing.

````
.class public abstract Landroid/util/proto/ProtoStream;
.super Ljava/lang/Object;
.source "ProtoStream.java"


# direct methods

.method public constructor greylist <init>()V
    .locals 0

    .prologue
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
````
### Steps to Reproduce

Unzip and same as above. Generates OOB.

[min.zip](https://github.com/iBotPeaches/Apktool/files/9922372/min.zip)

**Comment by RenateUSB** [comment]
Apparently a fix was merged??? https://github.com/JesusFreke/smali/pull/816
But the commit is not part of the git??? https://github.com/JesusFreke/smali/commit/3436508beafbbacf3aae5543cdd1f1eb5edf5017

**Comment by iBotPeaches** [comment]
@RenateUSB - Just looks like it was rebased/squashed - https://github.com/JesusFreke/smali/commit/81bd303a80b4413d4720243b2c80fb619d89bec8

@JesusFreke - You have a release planned soon for some of these merged, but unreleased fixes?

**Comment by RenateUSB** [comment]
Just to beat a dead horse...
In a dex file the classes must always have any super before a subclass.
So in that "min.zip" example above, the class order was:
```
HapiObject
ProtoStream
HapiProto
```
In the `hiddenapi_class_data_item` the hidden API flags are concatenated in order of class,
Unfortunately the current (incorrect) order that is being used is alphabetic.
In decoding the dex it's trying to decode the third set of flags (since HapiProto is last) and grabbing the flags for ProtoStream.
Moreover, since ProtoStream has less flags it's actually reading past the end of the valid flags.
It's grabbing a random 0x0e which when masked with 0x07 gives you the spurious 6 that is reported as error.
The fix?
```
HapiObject
ProtoStream
ZapiProto
```
This works fine. Now alphabetical order and class order match.
Ok, renaming classes might break something later...

**Comment by iBotPeaches** [comment]
I believe fixed with: https://github.com/iBotPeaches/Apktool/pull/2941

**Comment by r6680jc** [comment]
@RenateUSB

Have you tested apktool 2.7.0 to decompile and recompile framework.jar?

In my case, this issue still exists (same as self build smali/baksmali).

**Comment by RenateUSB** [comment]
@r6680jc No, not yet, but I'll check it out.
I have grown fond of directly patching 4 bytes in 30 M though.
https://github.com/iBotPeaches/Apktool/discussions/2947

**Comment by r6680jc** [comment]
@RenateUSB

It's just the resulting framework.jar with any classes.dex rebuilt without modification makes the device bootloop.
